### ISSUE TITLE
The "Look for updates" often fail in plug-in

### ISSUE THREAD

**Issue by hardolf** [hardolf/JRiver.MediaCenter#1]
Error in menu item: "HelpLookForUpdatesMenuItem" in MenuItem_Click event. 
    The request was aborted: Could not create SSL/TLS secure channel. 

The failure occurred in class object System 
when calling Method System.Net.WebResponse GetResponse().
 
Stack trace: 
   at System.Net.HttpWebRequest.GetResponse()
   at MediaCenter.LyricsFinder.Model.Helpers.Utility.UpdateCheck(Version currentVersion, Boolean isInteractive) in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\Model\Helpers\Utility.cs:line 146
   at MediaCenter.LyricsFinder.LyricsFinderCore.MenuItem_Click(Object sender, EventArgs e) in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.cs:line 555.

**Comment by hardolf** [comment]
Problem solved in release v1.1.1
