### ISSUE TITLE
Error in SearchAllStartStopButton_StartingAsync event. .     Exception: Automatic search all failed.

### ISSUE THREAD

**Issue by gurbina93** [hardolf/JRiver.MediaCenter#32]
I have been trying to get this thing working, now the playlists are loading and it seems like it's about to work but I get the following error.

```
Error in SearchAllStartStopButton_StartingAsync event. .
    Exception: Automatic search all failed.

The failure occurred in class object LyricsFinderCore

Inner exceptions: (all)
    Exception:     Process worker 0 failed at item 1.
    AggregateException:     One or more errors occurred.
    FileNotFoundException:     Could not load file or assembly 'Utility, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e8c6397ab74b1222' or one of its dependencies. The system cannot find the file specified.

Full exception details:
System.Exception: Automatic search all failed. ---> System.Exception: Process worker 0 failed at item 1.  ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Utility, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e8c6397ab74b1222' or one of its dependencies. The system cannot find the file specified.
   at MediaCenter.SharedComponents.MessageInspectorBehaviorExtensionElement.CreateBehavior()
   at System.ServiceModel.Description.ConfigLoader.LoadBehaviors[T](ServiceModelExtensionCollectionElement`1 behaviorElement, KeyedByTypeCollection`1 behaviors, Boolean commonBehaviors)
   at System.ServiceModel.Description.ConfigLoader.LoadChannelBehaviors(ServiceEndpoint serviceEndpoint, String configurationName)
   at System.ServiceModel.ChannelFactory.ApplyConfiguration(String configurationName, Configuration configuration)
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(String configurationName, EndpointAddress address, Configuration configuration)
   at System.ServiceModel.Configuration.ConfigurationChannelFactory`1..ctor(String endpointConfigurationName, Configuration configuration, EndpointAddress remoteAddress)
   at MediaCenter.LyricsFinder.Model.LyricServices.ChartLyricsService.<ProcessAsync>d__5.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricServices\ChartLyricsService\ChartLyricsService.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaCenter.LyricsFinder.Model.LyricServices.AbstractLyricService.<ProcessAsyncWrapper>d__94.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\Model\LyricServices\AbstractLyricService.cs:line 569
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MediaCenter.LyricsFinder.Model.LyricSearch.<>c.<SearchAsync>b__0_0(Task`1 t) in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\Model\LyricSearch.cs:line 105
   at MediaCenter.SharedComponents.AsyncUtility.<WhenAny>d__23`1.MoveNext() in D:\Projects\JRiver.MediaCenter\SharedComponents\Utility\AsyncUtility.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaCenter.LyricsFinder.Model.LyricSearch.<SearchAsync>d__0.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\Model\LyricSearch.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediaCenter.LyricsFinder.Model.LyricSearch.<SearchAsync>d__0.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\Model\LyricSearch.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllProcessWorkerAsync>d__202.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.Process.cs:line 411
   --- End of inner exception stack trace ---
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllProcessWorkerAsync>d__202.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.Process.cs:line 479
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllProcessAsync>d__201.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.Process.cs:line 302
   --- End of inner exception stack trace ---
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllProcessAsync>d__201.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.Process.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllProcessAsync>d__201.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.Process.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediaCenter.LyricsFinder.LyricsFinderCore.<SearchAllStartStopButton_StartingAsync>d__61.MoveNext() in D:\Projects\JRiver.MediaCenter\LyricsFinder\LyricsFinderCore\LyricsFinderCore.cs:line 1188
```
.

If I go song by song and click on search, it will throw the error and shortly it populates the lyrics. If I press search all it just throws the error.

JRiver MC 26.0

**Comment by hardolf** [comment]
Hi Glen,

I would like to know whether you experience the problem in the plug-in or the standalone application (or both)?
Also, how was the installation done? (e.g. using the released Setup.exe or manually)

As the error message states, you need the file "Utility.dll" in your installation folder.
The file is included in the "LyricsFinderFiles.1.3.3.zip" package file in the release.
The message indicates an incomplete installation.

You could try to copy the missing file(s) from the package file to your installation folder (preferably both Utility.dll and Utility.pdb files).

Regards, Bent

**Comment by gurbina93** [comment]
Happens in both.
I downloaded release LyricsFinder v1.3.3 and unzipped it. Then I ran the setup.exe.  I will follow up with your advice, and will report back to see if that fixes it!

**Comment by hardolf** [comment]
I failed to reproduce the problem using your procedure (after uninstalling the existing LyricsFinder) - it worked OK on my PC...
